version: '2'
services:
    apptrueque-app:
        image: apptrueque
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://apptrueque-postgresql:5432/apptrueque
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    apptrueque-postgresql:
        extends:
            file: postgresql.yml
            service: apptrueque-postgresql
