version: '2'
services:
    apptrueque-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/apptrueque/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=apptrueque
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
